from __future__ import annotations

import json, os, pathlib, re, shutil
from playwright.sync_api import expect, sync_playwright

ROOT=pathlib.Path(__file__).resolve().parents[1]
STATIC=ROOT/'services'/'core'/'app'/'static'
INDEX=re.sub(r'<script src="/static/app\.js\?v=[^"]+"></script>','',(STATIC/'index.html').read_text(encoding='utf-8'))
INDEX=re.sub(r'<link rel="stylesheet" href="/static/styles\.css\?v=[^"]+">','',INDEX)
ADMIN=re.sub(r'<script src="/static/admin\.js\?v=[^"]+"></script>','',(STATIC/'admin.html').read_text(encoding='utf-8'))
ACCOUNT=re.sub(r'<script src="/static/auth\.js\?v=[^"]+"></script>','',(STATIC/'account.html').read_text(encoding='utf-8'))
ACCOUNT=re.sub(r'<link rel="stylesheet" href="/static/styles\.css\?v=[^"]+">','',ACCOUNT)
APP=(STATIC/'app.js').read_text(encoding='utf-8');ADMIN_JS=(STATIC/'admin.js').read_text(encoding='utf-8');AUTH_JS=(STATIC/'auth.js').read_text(encoding='utf-8');CSS=(STATIC/'styles.css').read_text(encoding='utf-8')

BACKEND_STUB=r'''
window.__backend={
 routing:{auto:{provider_id:'local-ollama',model_id:'qwen3:0.6b'},fast:{provider_id:'local-ollama',model_id:'qwen3:0.6b'},smart:{provider_id:'local-ollama',model_id:'qwen3:0.6b'}},
 providers:[{id:'local-ollama',name:'Локальный Ollama',type:'ollama',base_url:'http://ollama:11434',enabled:1,managed_by:'system',has_secret:false,billing_class:'LOCAL',cost_input_per_million_rub:0,cost_output_per_million_rub:0}],
 inventory:[{provider_id:'local-ollama',provider_name:'Локальный Ollama',provider_type:'ollama',model_id:'qwen3:0.6b',display_name:'qwen3:0.6b',size:523000000,available:true,source:'discovery'},{provider_id:'local-ollama',provider_name:'Локальный Ollama',provider_type:'ollama',model_id:'qwen3:8b',display_name:'qwen3:8b',size:5200000000,available:true,source:'discovery'},{provider_id:'local-ollama',provider_name:'Локальный Ollama',provider_type:'ollama',model_id:'<img src=x onerror=window.__parXssAdmin=1>',display_name:'<img src=x onerror=window.__parXssAdmin=1>',size:123,available:true,source:'discovery'}],
 jobs:{},codeJobs:{},tasks:{},deployments:[],showTokens:false,lastMode:null,lastPreset:null,lastFileIds:[],chatCalls:0,users:[],artifacts:[]
};
window.fetch=async function(url,opts={}){
 const path=String(url),method=(opts.method||'GET').toUpperCase();let body={};try{body=opts.body?JSON.parse(opts.body):{}}catch(_){}
 const auth=(opts.headers&&((opts.headers.Authorization)||(opts.headers['Authorization'])))||'';let status=200,payload={};
 if(path==='/api/system')payload={product:'Personal Agent Rus',version:'0.7.2',modes:[{id:'auto',label:'Авто',description:'Баланс'},{id:'fast',label:'Быстро',description:'Коротко'},{id:'smart',label:'Умно',description:'Глубже'}],presets:[{id:'explain',label:'Объяснить'},{id:'write',label:'Написать'},{id:'analyze',label:'Проанализировать'}],capabilities:{chat:{status:'ready',label:'Чат'},web:{status:'ready',label:'Веб'},research:{status:'ready',label:'Исследование'},files:{status:'ready',label:'Файлы'},code:{status:'ready',label:'Код'},billing:{status:'ready',label:'Подписка'},tasks:{status:'ready',label:'Задачи'},deployment:{status:'admin',label:'Развёртывание'},media:{status:'planned',label:'Медиа'}},auth:{mode:'personal',registration_policy:'open'},setup_complete:false};
 else if(path==='/api/auth/me')payload={ok:true,mode:'personal',registration_policy:'open',user:{id:'local-owner',display_name:'Локальный пользователь',role:'USER'}};
 else if(path==='/api/billing/plans')payload={plans:[{id:'LIGHT',display_name:'Лайт',price_rub:0,support_level:'community',local_unlimited:true,remote_token_limit:0,remote_cost_limit_rub:0,enabled:true},{id:'MEDIUM',display_name:'Медиум',price_rub:500,support_level:'standard',local_unlimited:true,remote_token_limit:100000,remote_cost_limit_rub:50,enabled:true},{id:'PRO',display_name:'Про',price_rub:1000,support_level:'priority',local_unlimited:true,remote_token_limit:500000,remote_cost_limit_rub:250,enabled:true}]};
 else if(path==='/api/billing/me')payload={plan:{id:'LIGHT',display_name:'Лайт',price_rub:0,support_level:'community',local_unlimited:true,remote_token_limit:0,remote_cost_limit_rub:0,enabled:true},subscription:{plan_id:'LIGHT',status:'ACTIVE',auto_renew:false,cancel_at_period_end:false,billing_exempt:false},usage:{by_class:{LOCAL:{total_tokens:1250,estimated_cost_rub:0}},total:{total_tokens:1250,estimated_cost_rub:0}},quota:{platform_remote_tokens_used:0,platform_remote_tokens_limit:0,platform_remote_tokens_remaining:0,platform_remote_cost_rub_used:0,platform_remote_cost_rub_limit:0,platform_remote_cost_rub_remaining:0},preferences:{show_token_usage:window.__backend.showTokens},payment:{configured:false,provider:'disabled'}};
 else if(path==='/api/billing/preferences'&&method==='POST'){window.__backend.showTokens=!!body.show_token_usage;payload={show_token_usage:window.__backend.showTokens};}
 else if(path==='/api/billing/checkout'&&method==='POST'){status=503;payload={error:'payment provider is not configured'};}
 else if(path==='/api/health')payload={ready:true,engine:'ready',inference:'ready'};
 else if(path==='/api/chat'){window.__backend.chatCalls++;const latest=(body.messages||[]).filter(x=>x.role==='user').at(-1)?.content||'';window.__backend.lastMode=body.mode;window.__backend.lastPreset=body.preset||'none';window.__backend.lastFileIds=body.file_ids||[];let text='PAR_TEST_OK',sources=[];if(String(latest).includes('PAR_XSS'))text='<img src=x onerror=window.__parXss=1>';if(String(latest).includes('PAR_MARKDOWN'))text='### Ответ\n\n**Жирный** текст и `код`.\n\n```python\nprint("ok")\n```';if(String(latest).trim().toLowerCase()==='ок')text='Хорошо.';if(String(latest).includes('https://')||body.intent_hint==='search'||body.intent_hint==='research'){text='PAR_WEB_OK';sources=[{title:'DTF fixture',url:'https://dtf.ru/test',status:'retrieved',strategy:'browser'},{title:'Second source',url:'https://example.org/second',status:'retrieved',strategy:'static'}]};payload={ok:true,message:{role:'assistant',content:text},mode:body.mode,preset:body.preset||'none',intent:sources.length?(body.intent_hint||'url'):'chat',sources};}
 else if(path==='/api/tasks'&&method==='POST'){const id='t'+String(Object.keys(window.__backend.tasks).length+1).padStart(31,'0');const task={id,user_id:'local-owner',task_type:'research_report',title:body.question,status:'RUNNING',phase:'web',progress:20,result:null,steps:[]};window.__backend.tasks[id]=task;setTimeout(()=>{window.__backend.tasks[id]={...task,status:'COMPLETED',phase:'completed',progress:100,result:{answer:'REPORT_OK',sources:[{title:'Source',url:'https://example.org/source',status:'retrieved'}],artifacts:[{id:'a1',name:'research-report.md',mime:'text/markdown',sha256:'a'.repeat(64),validation_status:'verified'},{id:'a2',name:'research-sources.xlsx',mime:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',sha256:'b'.repeat(64),validation_status:'verified'},{id:'a3',name:'research-report.pdf',mime:'application/pdf',sha256:'c'.repeat(64),validation_status:'verified'}]}}},80);status=202;payload={ok:true,task};}
 else if(path.startsWith('/api/tasks/')&&method==='GET'){const id=path.split('/')[3];payload={ok:true,task:window.__backend.tasks[id]};}
 else if(path.startsWith('/api/tasks/')&&path.endsWith('/cancel')&&method==='POST'){const id=path.split('/')[3];window.__backend.tasks[id]={...(window.__backend.tasks[id]||{id}),status:'CANCELLED',phase:'cancelled',progress:100};payload={ok:true,cancel_requested:true,task:window.__backend.tasks[id]};}
 else if(path.startsWith('/api/tasks?')&&method==='GET'){payload={ok:true,tasks:Object.values(window.__backend.tasks)};}
 else if(path==='/api/code/status')payload={ok:true,ready:true,network:'disabled',languages:[{id:'python',label:'Python',available:true},{id:'java',label:'Java 21',available:true},{id:'powershell',label:'PowerShell',available:true}]};
 else if(path==='/api/code/jobs'&&method==='POST'){const id='c'+String(Object.keys(window.__backend.codeJobs).length+1).padStart(31,'0');const job={id,language:body.language,status:'QUEUED',progress:0,error:null};window.__backend.codeJobs[id]=job;setTimeout(()=>{window.__backend.codeJobs[id]={...job,status:'COMPLETED',progress:100,result:{exit_code:0,duration_ms:12,stdout:'CODE_OK\n',stderr:'',output_truncated:false,timed_out:false,cancelled:false}}},80);status=202;payload={ok:true,job};}
 else if(path.startsWith('/api/code/jobs/')&&path.endsWith('/cancel')&&method==='POST'){const id=path.split('/')[4];window.__backend.codeJobs[id]={...(window.__backend.codeJobs[id]||{id}),status:'CANCELLED',progress:100,error:'cancelled'};payload={ok:true,job:window.__backend.codeJobs[id]};}
 else if(path.startsWith('/api/code/jobs/')&&method==='GET'){const id=path.split('/').at(-1);payload={ok:true,job:window.__backend.codeJobs[id]||{id,status:'FAILED',error:'missing'}};}
 else if(path==='/api/files'&&method==='GET')payload={ok:true,artifacts:JSON.parse(JSON.stringify(window.__backend.artifacts))};
 else if(path==='/api/files/upload'&&method==='POST'){const id='file-'+(window.__backend.artifacts.length+1);const item={artifact_id:id,name:'fixture.txt',format:'txt',size:42,version:1,validation_status:'verified',sha256:'a'.repeat(64),download_url:'/api/files/'+id+'/download'};window.__backend.artifacts.unshift(item);status=201;payload={ok:true,artifact:item};}
 else if(path==='/api/files/create'&&method==='POST'){const id='file-'+(window.__backend.artifacts.length+1);const item={artifact_id:id,name:body.name||('document.'+body.format),format:body.format,size:128,version:1,validation_status:'verified',sha256:'b'.repeat(64),download_url:'/api/files/'+id+'/download'};window.__backend.artifacts.unshift(item);status=201;payload={ok:true,artifact:item};}
 else if(path.startsWith('/api/files/')&&method==='DELETE'){const id=path.split('/').at(-1);window.__backend.artifacts=window.__backend.artifacts.filter(x=>x.artifact_id!==id);payload={ok:true};}
 else if(path==='/api/admin/login'){if(body.token!=='browser-admin-token-123'){status=401;payload={error:'invalid admin token'}}else payload={ok:true};}
 else if(path==='/api/admin/status'){if(auth!=='Bearer browser-admin-token-123'){status=401;payload={error:'admin authorization required'}}else payload={product:'Personal Agent Rus',product_family:'Personal Agent',edition:'rus',locale:'ru-RU',version:'0.7.2',bootstrap_model:'qwen3:0.6b',routing:JSON.parse(JSON.stringify(window.__backend.routing)),providers:JSON.parse(JSON.stringify(window.__backend.providers)),provider_status:window.__backend.providers.map(p=>({provider_id:p.id,healthy:true,model_count:window.__backend.inventory.filter(m=>m.provider_id===p.id).length,error:null})),model_inventory:JSON.parse(JSON.stringify(window.__backend.inventory)),installed_models:window.__backend.inventory.filter(m=>m.provider_id==='local-ollama').map(m=>({name:m.model_id,size:m.size})),auth_mode:'personal',registration_policy:'open',setup_complete:false};}
 else if(path==='/api/admin/users'){if(auth!=='Bearer browser-admin-token-123'){status=401;payload={error:'admin authorization required'}}else payload={users:window.__backend.users,auth_mode:'personal',registration_policy:'open'};}
 else if(path==='/api/admin/billing'){if(auth!=='Bearer browser-admin-token-123'){status=401;payload={error:'admin authorization required'}}else payload={plans:[{id:'LIGHT',display_name:'Лайт',price_rub:0,support_level:'community',local_unlimited:true,remote_token_limit:0,remote_cost_limit_rub:0},{id:'MEDIUM',display_name:'Медиум',price_rub:500,support_level:'standard',local_unlimited:true,remote_token_limit:100000,remote_cost_limit_rub:50},{id:'PRO',display_name:'Про',price_rub:1000,support_level:'priority',local_unlimited:true,remote_token_limit:500000,remote_cost_limit_rub:250}],payment_config:{provider:'disabled',shop_id:'',public_base_url:'',has_secret:false,configured:false,webhook_path:'/api/billing/webhook/yookassa'},usage:[{billing_class:'LOCAL',provider_id:'local-ollama',model_id:'qwen3:0.6b',tokens:1250,estimated_cost_rub:0,events:2}]};}
 else if(path.startsWith('/api/admin/billing/plans/')&&method==='POST'){payload={ok:true,plan:{id:path.split('/').at(-1),remote_token_limit:Number(body.remote_token_limit||0),remote_cost_limit_rub:Number(body.remote_cost_limit_rub||0)}};}
 else if(path==='/api/admin/billing/payment-config'&&method==='POST'){payload={ok:true,payment_config:{provider:body.provider||'disabled',shop_id:body.shop_id||'',public_base_url:body.public_base_url||'',has_secret:Boolean(body.secret_key),configured:(body.provider==='yookassa'&&Boolean(body.shop_id&&body.public_base_url&&body.secret_key)),webhook_path:'/api/billing/webhook/yookassa'}};}
 else if(path==='/api/admin/observability'){payload={ok:true,observability:{version:'0.7.2',runtime_profile:'local',uptime_seconds:123,load:[0.1,0.2,0.3],disk:{free_bytes:1000,total_bytes:2000},db_size_bytes:1234,counts:{tasks_active:0,artifacts:3}}};}
 else if(path==='/api/admin/deployments/fingerprint'&&method==='POST'){payload={ok:true,fingerprint:{type:'ssh-ed25519',sha256:'SHA256:BROWSERTEST'}};}
 else if(path==='/api/admin/deployments'&&method==='POST'){const item={id:'d'+String(window.__backend.deployments.length+1).padStart(31,'0'),name:body.name,host:body.host,port:body.port,username:body.username,domain:body.domain,profile:body.profile,host_key_sha256:body.host_key_sha256,last_status:'NEW',last_message:''};window.__backend.deployments.push(item);status=201;payload={ok:true,target:item};}
 else if(path==='/api/admin/deployments'&&method==='GET'){payload={ok:true,targets:window.__backend.deployments,profiles:[{id:'server-lite',label:'Слабый VPS'},{id:'server-standard',label:'Обычный VPS'}]};}
 else if(path==='/api/admin/providers'){if(auth!=='Bearer browser-admin-token-123'){status=401;payload={error:'admin authorization required'}}else if(method==='POST'){const id='provider-test';window.__backend.providers.push({id,name:body.name,type:body.type,base_url:body.base_url,enabled:1,managed_by:'admin',has_secret:Boolean(body.api_key),billing_class:body.billing_class||'BYOK',cost_input_per_million_rub:Number(body.cost_input_per_million_rub||0),cost_output_per_million_rub:Number(body.cost_output_per_million_rub||0)});window.__backend.inventory.push({provider_id:id,provider_name:body.name,provider_type:body.type,model_id:'external-model',display_name:'external-model',size:0,available:true,source:'discovery'});status=201;payload={ok:true,provider:{id,name:body.name,type:body.type,base_url:body.base_url,model_count:1,has_secret:Boolean(body.api_key)}}}else payload={providers:window.__backend.providers,inventory:window.__backend.inventory};}
 else if(path.startsWith('/api/admin/providers/')&&path.endsWith('/test'))payload={ok:true,provider_id:path.split('/').at(-2),model_count:1};
 else if(path.startsWith('/api/admin/providers/')&&method==='DELETE'){const id=path.split('/').at(-1);window.__backend.providers=window.__backend.providers.filter(p=>p.id!==id);window.__backend.inventory=window.__backend.inventory.filter(m=>m.provider_id!==id);payload={ok:true};}
 else if(path==='/api/admin/routing'&&method==='POST'){window.__backend.routing={...window.__backend.routing,...body.routing};payload={ok:true};}
 else if(path==='/api/admin/models/pull'&&method==='POST'){window.__backend.inventory.push({provider_id:body.provider_id||'local-ollama',provider_name:'Локальный Ollama',provider_type:'ollama',model_id:body.model,display_name:body.model,size:1000000,available:true,source:'discovery'});window.__backend.jobs.j1={id:'j1',status:'completed',progress:100,message:'Модель готова'};status=202;payload={ok:true,job_id:'j1'};}
 else if(path==='/api/admin/jobs/j1')payload=window.__backend.jobs.j1;
 else{status=404;payload={error:'not found'}}
 return new Response(JSON.stringify(payload),{status,headers:{'Content-Type':'application/json'}});
};
'''

def chromium_path():
    override=os.getenv('PA_TEST_CHROMIUM')
    if override:return override
    for name in ('chromium','chromium-browser','google-chrome','google-chrome-stable'):
        path=shutil.which(name)
        if path:return path
    return None

def install_storage(page,name,initial=None):
    initial=initial or {};script=f"Object.defineProperty(window,{json.dumps(name)},{{configurable:true,value:{{d:{json.dumps(initial,ensure_ascii=False)},setItem(k,v){{this.d[k]=String(v)}},getItem(k){{return Object.prototype.hasOwnProperty.call(this.d,k)?this.d[k]:null}},removeItem(k){{delete this.d[k]}},clear(){{this.d={{}}}}}}}});";page.evaluate(script)

def load_user(page,storage=None):
    page.set_content(INDEX);install_storage(page,'localStorage',storage);install_storage(page,'sessionStorage',{});page.add_style_tag(content=CSS);page.add_script_tag(content=BACKEND_STUB);page.add_script_tag(content=APP);expect(page.locator('.mode')).to_have_count(3)

def load_admin(page,storage=None):
    page.set_content(ADMIN);install_storage(page,'sessionStorage',storage);page.add_style_tag(content=CSS);page.add_script_tag(content=BACKEND_STUB);page.add_script_tag(content=ADMIN_JS)

def load_account(page):
    page.set_content(ACCOUNT);page.add_style_tag(content=CSS);page.add_script_tag(content=BACKEND_STUB);page.add_script_tag(content=AUTH_JS)

def main():
    exe=chromium_path()
    if not exe:raise SystemExit('No Chromium/Chrome executable found; set PA_TEST_CHROMIUM')
    with sync_playwright() as p:
        browser=p.chromium.launch(headless=True,executable_path=exe,args=['--no-sandbox'])
        page=browser.new_page(viewport={'width':1440,'height':900});load_user(page)
        assert page.title()=='Personal Agent Rus';body=page.locator('body').inner_text().lower();assert page.locator('#sidebar').is_visible();assert page.locator('#accountEntry').is_visible();assert page.locator('a[href="/admin"]').count()>=1
        for secret in ('qwen','ollama','provider_id','model_id'):assert secret not in body,secret
        # Structured preset is independent from Smart mode.
        page.locator('.starter-card[data-preset="analyze"]').click();page.get_by_role('button',name='Умно',exact=True).click();page.locator('#input').fill('ок');page.locator('#send').click();expect(page.locator('.msg.assistant')).to_have_count(1);assert 'Хорошо' in page.locator('.msg.assistant').last.inner_text();assert page.evaluate('window.__backend.lastMode')=='smart';assert page.evaluate('window.__backend.lastPreset')=='analyze'
        page.locator('#input').fill('PAR_MARKDOWN');page.locator('#send').click();expect(page.locator('.code-block')).to_have_count(1)
        page.locator('#newChat').click();page.locator('.starter-card[data-intent="research"]').click();page.locator('#input').fill('Что нового на https://dtf.ru/');page.locator('#send').click();expect(page.locator('.msg.assistant')).to_have_count(1);expect(page.locator('.message-sources .source-card')).to_have_count(2);assert 'PAR_WEB_OK' in page.locator('.msg.assistant').last.inner_text()
        # Real Files UI journey: tool -> upload -> attachment -> chat context -> workspace list -> create.
        page.locator('#attachBtn').click();expect(page.locator('#toolTray')).to_be_visible();page.locator('[data-tool="files"]').click();page.locator('#fileInput').set_input_files({'name':'notes.txt','mimeType':'text/plain','buffer':b'fixture text'});expect(page.locator('#attachmentBar .attachment-chip')).to_have_count(1);page.locator('#input').fill('Проанализируй файл');page.locator('#send').click();expect(page.locator('.message-attachments .message-file')).to_have_count(1);assert page.evaluate('window.__backend.lastFileIds.length')==1
        page.locator('#filesEntry').click();expect(page.locator('[data-settings-panel="files"]')).to_have_class(re.compile('active'));expect(page.locator('#artifactList .artifact-row')).to_have_count(1);page.locator('#artifactFormat').select_option('pdf');page.locator('#artifactName').fill('report.pdf');page.locator('#artifactContent').fill('Тестовый PDF');page.locator('#createArtifact').click();expect(page.locator('#artifactList .artifact-row')).to_have_count(2);page.locator('#closeSettings').click()
        # Code UI journey: open sandbox, execute, poll result.
        page.locator('#codeEntry').click();expect(page.locator('[data-settings-panel="code"]')).to_have_class(re.compile('active'));expect(page.locator('#codeRunState')).to_contain_text('Sandbox');page.locator('#codeLanguage').select_option('python');page.locator('#codeEditor').fill('print("CODE_OK")');page.locator('#runCode').click();expect(page.locator('#codeStdout')).to_contain_text('CODE_OK',timeout=5000);expect(page.locator('#codeRunState')).to_contain_text('COMPLETED');page.locator('#closeSettings').click()
        page.locator('#newChat').click();page.locator('#input').fill('Второй отдельный диалог');page.locator('#send').click();page.locator('#chatMenuButton').click();page.locator('#chatMenu [data-action="rename"]').click();page.locator('#actionInput').fill('Рабочий чат');page.locator('#actionConfirm').click();expect(page.locator('#conversationTitle')).to_have_text('Рабочий чат');page.locator('#chatSearch').fill('Рабочий');expect(page.locator('.conversation-item')).to_have_count(1);page.locator('#chatSearch').fill('')
        page.locator('#settingsEntry').click();expect(page.locator('#settingsBackdrop')).to_be_visible();page.locator('#closeSettings').click()
        before_xss=page.locator('.msg.assistant').count();page.locator('#input').fill('PAR_XSS');page.locator('#send').click();expect(page.locator('.msg.assistant')).to_have_count(before_xss+1);assert '<img src=x onerror=window.__parXss=1>' in page.locator('.msg.assistant').last.inner_text();assert page.locator('#chat img').count()==0;assert page.evaluate('window.__parXss') is None
        mobile=browser.new_page(viewport={'width':390,'height':844});load_user(mobile);mobile.locator('#openSidebar').click();mobile.wait_for_timeout(260);expect(mobile.locator('#sidebar')).to_be_visible();assert mobile.locator('#accountEntry').count()==1 and mobile.locator('a[href="/admin"]').count()>=1
        account=browser.new_page(viewport={'width':1100,'height':800});load_account(account);expect(account.locator('#billingAccount')).to_be_visible();expect(account.locator('#currentPlan')).to_have_text('Лайт');prices=account.locator('.plan-price').all_inner_texts();assert 'Бесплатно' in prices and '500 ₽/мес' in prices and '1000 ₽/мес' in prices;assert 'Локально' in account.locator('#usageSummary').inner_text();account.locator('#showTokens').check();assert account.evaluate('window.__backend.showTokens') is True
        admin=browser.new_page(viewport={'width':1280,'height':900});load_admin(admin);admin.locator('#token').fill('browser-admin-token-123');admin.locator('#loginBtn').click();admin.locator('#admin').wait_for(state='visible')
        for name in ('Обзор','Провайдеры','Модели','Маршрутизация','Пользователи','Тарифы и Usage','VPS / Deploy','Мониторинг','Система'):assert admin.get_by_role('button',name=name,exact=True).is_visible(),name
        admin.get_by_role('button',name='Провайдеры',exact=True).click();assert 'Локальный Ollama' in admin.locator('#providers').inner_text();admin.locator('#providerName').fill('LM Studio');admin.locator('#providerUrl').fill('http://host.docker.internal:1234/v1');admin.locator('#providerKey').fill('secret-not-rendered');admin.locator('#providerBillingClass').select_option('PLATFORM_REMOTE');admin.locator('#providerInputCost').fill('10');admin.locator('#providerOutputCost').fill('20');admin.locator('#addProvider').click();expect(admin.locator('#providerState')).to_contain_text('Подключено')
        admin.get_by_role('button',name='Модели',exact=True).click();assert 'external-model' in admin.locator('#models').inner_text();assert '<img src=x onerror=window.__parXssAdmin=1>' in admin.locator('#models').inner_text();assert admin.locator('#models img').count()==0;assert admin.evaluate('window.__parXssAdmin') is None
        admin.get_by_role('button',name='Маршрутизация',exact=True).click();smart=admin.locator('select[data-mode="smart"]');smart.select_option('provider-test\u0000external-model');admin.locator('#saveRoutes').click();expect(admin.locator('#saveState')).to_contain_text('Сохранено');route=admin.evaluate('window.__backend.routing.smart');assert route['provider_id']=='provider-test' and route['model_id']=='external-model'
        admin.get_by_role('button',name='Пользователи',exact=True).click();assert 'Personal-профиль' in admin.locator('#users').inner_text()
        admin.get_by_role('button',name='Тарифы и Usage',exact=True).click();expect(admin.locator('#billingPlans .billing-plan-row')).to_have_count(3);assert '500 ₽/мес' in admin.locator('#billingPlans').inner_text() and '1000 ₽/мес' in admin.locator('#billingPlans').inner_text();assert 'LOCAL' in admin.locator('#billingUsage').inner_text();assert admin.locator('#billingSecret').get_attribute('type')=='password'
        admin.get_by_role('button',name='VPS / Deploy',exact=True).click();assert admin.locator('#deployBootstrap').is_visible();expect(admin.locator('#deployProvider')).to_contain_text('LM Studio');admin.locator('#deployProvider').select_option('provider-test');admin.locator('#deployName').fill('Browser VPS');admin.locator('#deployHost').fill('203.0.113.10');admin.locator('#deployUser').fill('deploy');admin.locator('#deployDomain').fill('agent.example.test');admin.locator('#fetchDeployFingerprint').click();expect(admin.locator('#deployFingerprint')).to_have_value('SHA256:BROWSERTEST');admin.locator('#saveDeployTarget').click();expect(admin.locator('#deploymentTargets .provider-card')).to_have_count(1)
        admin.get_by_role('button',name='Мониторинг',exact=True).click();admin.locator('#refreshMonitoring').click();expect(admin.locator('#monitoringOutput')).to_contain_text('uptime_seconds')
        browser.close()
    print('PAR_V072_BROWSER_ACCEPTANCE PASS: shell presets web-research files code-sandbox tasks history mobile admin providers routing users billing deployment monitoring xss')
    return 0

if __name__=='__main__':raise SystemExit(main())
