"""Privileged production tier check with a temporary, non-login test account.

Runs inside Core; uses real local/OpenAI inference, creates no payments, sends no
email, and removes only rows belonging to the UUID generated by this run.
"""
import json
import sys
import urllib.error
import urllib.request
import uuid

sys.path.insert(0, "/app")
import main as app

uid = uuid.uuid4().hex
with app.db() as conn:
    conn.execute(
        "INSERT INTO users(id,email,display_name,password_hash,role,status,email_verified,created_at,updated_at) VALUES(?,?,?,'!','USER','active',1,?,?)",
        (uid, uid + "@example.invalid", "Temporary tier acceptance", app.now_ts(), app.now_ts()),
    )
    conn.commit()
token, _ = app.create_session(uid, ip="127.0.0.1", user_agent="Tier acceptance")
headers = {"Cookie": "pa_session=" + token, "X-CSRF-Token": app.csrf_token_for_session(token), "Content-Type": "application/json"}


def call(path, body=None, expected=200):
    req = urllib.request.Request("http://127.0.0.1:8080" + path, headers=headers,
                                 data=json.dumps(body).encode() if body is not None else None)
    try:
        with urllib.request.urlopen(req, timeout=120) as response:
            status, result = response.status, json.load(response)
    except urllib.error.HTTPError as exc:
        status, result = exc.code, json.load(exc)
    assert status == expected, (path, status, result.get("error"))
    return result


try:
    call("/api/billing/preferences", {"show_token_usage": True})
    call("/api/files", expected=403)
    call("/api/web/search", {"query": "test"}, expected=403)
    answer = call("/api/chat", {"mode": "fast", "messages": [{"role": "user", "content": "Reply with just OK."}]})
    assert answer["message"]["content"].strip() and answer["usage"]["billing_class"] == "LOCAL"
    print("PASS production LIGHT: real local answer, files and search denied", flush=True)
    app.BILLING.assign_plan(uid, "MEDIUM")
    before = call("/api/billing/me")
    answer = call("/api/chat", {"mode": "fast", "messages": [{"role": "user", "content": "Reply with just OK."}]})
    after = call("/api/billing/me")
    assert answer["usage"]["billing_class"] == "PLATFORM_REMOTE"
    assert after["quota"]["platform_remote_tokens_remaining"] < before["quota"]["platform_remote_tokens_remaining"]
    assert after["balance"]["balance_rub"] == 0
    print("PASS production MEDIUM: real OpenAI answer, remote token quota debited, wallet unchanged", flush=True)
finally:
    with app.db() as conn:
        for table in ("sessions", "subscriptions", "usage_events", "billing_preferences", "user_experience_preferences", "scenario_states"):
            conn.execute(f"DELETE FROM {table} WHERE user_id=?", (uid,))
        conn.execute("DELETE FROM users WHERE id=?", (uid,))
        conn.commit()
    print("PASS cleanup: temporary tier account removed", flush=True)
