from __future__ import annotations

import json, os, pathlib, re, shutil
from playwright.sync_api import expect, sync_playwright

ROOT=pathlib.Path(__file__).resolve().parents[1]
STATIC=ROOT/'services'/'core'/'app'/'static'
INDEX=re.sub(r'<script src="/static/app\.js\?v=[^"]+"></script>','',(STATIC/'index.html').read_text(encoding='utf-8'))
INDEX=re.sub(r'<link rel="stylesheet" href="/static/styles\.css\?v=[^"]+">','',INDEX)
ADMIN=re.sub(r'<script src="/static/admin\.js\?v=[^"]+"></script>','',(STATIC/'admin.html').read_text(encoding='utf-8'))
ACCOUNT=re.sub(r'<script src="/static/auth\.js\?v=[^"]+"></script>','',(STATIC/'account.html').read_text(encoding='utf-8'))
ACCOUNT=re.sub(r'<link rel="stylesheet" href="/static/styles\.css\?v=[^"]+">','',ACCOUNT)
APP=(STATIC/'app.js').read_text(encoding='utf-8');ADMIN_JS=(STATIC/'admin.js').read_text(encoding='utf-8');AUTH_JS=(STATIC/'auth.js').read_text(encoding='utf-8');CSS=(STATIC/'styles.css').read_text(encoding='utf-8')

BACKEND_STUB=r'''
window.__backend={
 routing:{auto:{provider_id:'local-ollama',model_id:'qwen3:0.6b'},fast:{provider_id:'local-ollama',model_id:'qwen3:0.6b'},smart:{provider_id:'local-ollama',model_id:'qwen3:0.6b'}},
 providers:[{id:'local-ollama',name:'Локальный Ollama',type:'ollama',base_url:'http://ollama:11434',enabled:1,managed_by:'system',has_secret:false,billing_class:'LOCAL',cost_input_per_million_rub:0,cost_output_per_million_rub:0}],
 inventory:[{provider_id:'local-ollama',provider_name:'Локальный Ollama',provider_type:'ollama',model_id:'qwen3:0.6b',display_name:'qwen3:0.6b',size:523000000,available:true,source:'discovery'},{provider_id:'local-ollama',provider_name:'Локальный Ollama',provider_type:'ollama',model_id:'qwen3:8b',display_name:'qwen3:8b',size:5200000000,available:true,source:'discovery'},{provider_id:'local-ollama',provider_name:'Локальный Ollama',provider_type:'ollama',model_id:'<img src=x onerror=window.__parXssAdmin=1>',display_name:'<img src=x onerror=window.__parXssAdmin=1>',size:123,available:true,source:'discovery'}],
 jobs:{},codeJobs:{},tasks:{},deployments:[],authMode:'personal',authRole:'OWNER',showTokens:false,lastMode:null,lastPreset:null,lastFileIds:[],chatCalls:0,users:[],artifacts:[],conversations:[],folders:[],onboarding:{user:{status:'completed',current_step:8,tour_version:1},admin:{status:'completed',current_step:6,tour_version:1}},
 scenarios:[{id:'clothing',title:'Подобрать одежду',description:'Найти вещи по размеру, бюджету и стилю',category:'life',icon:'◫',required_capabilities:['web'],example_prompt:'Подбери мне одежду под мои параметры и бюджет.',max_clarification_rounds:1},{id:'procurement',title:'Найти закупки',description:'Найти подходящие закупки и тендеры',category:'work',icon:'▤',required_capabilities:['web','research'],example_prompt:'Найди подходящие закупки по моей теме.',max_clarification_rounds:2}],
 webPreferences:{search_scope:'internet',prefer_russian:true,region:'',allowed_domains:[],excluded_domains:[]},experiencePreferences:{ui_language:'ru',response_language:'auto',theme:'system',execution_policy:'auto',tone:'normal'},feedback:[],shares:[],
 siteProfiles:[{id:'cian',domain_pattern:'cian.ru',category:'real_estate',acquisition_order:'search,browser,static',egress_region:'ru',enabled:true},{id:'zakupki',domain_pattern:'zakupki.gov.ru',category:'procurement',acquisition_order:'search,browser,static',egress_region:'ru',enabled:true}],scenarioPending:{}
};
window.fetch=async function(url,opts={}){
 const path=String(url),method=(opts.method||'GET').toUpperCase();let body={};try{body=opts.body?JSON.parse(opts.body):{}}catch(_){}
 const auth=(opts.headers&&((opts.headers.Authorization)||(opts.headers['Authorization'])))||'';const adminOk=auth==='Bearer browser-admin-token-123'||(window.__backend.authMode==='personal'&&window.__backend.authRole==='OWNER')||(window.__backend.authMode==='accounts'&&['OWNER','ADMIN'].includes(window.__backend.authRole));let status=200,payload={};
 if(path==='/api/system')payload={product:'Personal Agent Rus',version:'0.8.0-alpha.8',modes:[{id:'auto',label:'Авто',description:'Баланс'},{id:'fast',label:'Быстро',description:'Коротко'},{id:'smart',label:'Умно',description:'Глубже'}],presets:[{id:'explain',label:'Объяснить'},{id:'write',label:'Написать'},{id:'analyze',label:'Проанализировать'}],tones:[{id:'normal',label:'Обычный'},{id:'friendly',label:'Дружелюбный'},{id:'ironic',label:'С иронией'},{id:'meme',label:'Мемный'},{id:'serious',label:'Очень серьёзный'},{id:'expert',label:'Экспертный'},{id:'brief',label:'Кратко'},{id:'detailed',label:'Подробно'}],execution_policies:[{id:'auto'},{id:'local_only'},{id:'prefer_local'},{id:'remote_allowed'},{id:'remote_only'}],languages:{ui:['ru','en'],response:['auto','ru','en']},capabilities:{chat:{status:'ready',label:'Чат'},web:{status:'ready',label:'Веб'},research:{status:'ready',label:'Исследование'},files:{status:'ready',label:'Файлы'},code:{status:'ready',label:'Код'},billing:{status:'ready',label:'Подписка'},tasks:{status:'ready',label:'Задачи'},deployment:{status:'admin',label:'Развёртывание'},media:{status:'planned',label:'Медиа'}},auth:{mode:window.__backend.authMode,registration_policy:'open'},setup_complete:false};
 else if(path==='/api/auth/me')payload={ok:true,mode:window.__backend.authMode,registration_policy:'open',csrf_token:'browser-csrf',user:{id:'local-owner',display_name:'Локальный пользователь',role:window.__backend.authRole}};
 else if(path==='/api/scenarios')payload={ok:true,scenarios:JSON.parse(JSON.stringify(window.__backend.scenarios))};
 else if(path==='/api/preferences/web'&&method==='GET')payload={ok:true,preferences:JSON.parse(JSON.stringify(window.__backend.webPreferences))};
 else if(path==='/api/preferences/web'&&method==='POST'){window.__backend.webPreferences={search_scope:body.search_scope||'internet',prefer_russian:body.prefer_russian!==false,region:body.region||'',allowed_domains:body.allowed_domains||[],excluded_domains:body.excluded_domains||[]};payload={ok:true,preferences:JSON.parse(JSON.stringify(window.__backend.webPreferences))};}
 else if(path==='/api/preferences/experience'&&method==='GET')payload={ok:true,preferences:JSON.parse(JSON.stringify(window.__backend.experiencePreferences))};
 else if(path==='/api/preferences/experience'&&method==='POST'){window.__backend.experiencePreferences={...window.__backend.experiencePreferences,...body};payload={ok:true,preferences:JSON.parse(JSON.stringify(window.__backend.experiencePreferences))};}
 else if(path==='/api/feedback'&&method==='POST'){const item={id:'fb-'+(window.__backend.feedback.length+1),user_id:'local-owner',category:body.category||'other',rating:body.rating||null,message:body.message||'',page:body.page||'',status:'new',created_at:Math.floor(Date.now()/1000)};window.__backend.feedback.unshift(item);status=201;payload={ok:true,feedback:item};}
 else if(path==='/api/conversations/export'&&method==='GET'){payload={ok:true,export:{schema_version:1,folders:JSON.parse(JSON.stringify(window.__backend.folders)),conversations:JSON.parse(JSON.stringify(window.__backend.conversations))}};}
 else if(path.startsWith('/api/conversations')&&method==='GET'){
   const parts=path.split('?')[0].split('/').filter(Boolean);if(parts.length===3){const c=window.__backend.conversations.find(x=>x.id===parts[2]);if(!c){status=404;payload={error:'conversation not found'}}else payload={ok:true,conversation:JSON.parse(JSON.stringify(c))}}else{const q=new URL('http://x'+path).searchParams.get('q')||'';const list=window.__backend.conversations.filter(c=>!q||c.title.toLowerCase().includes(q.toLowerCase())||c.messages.some(m=>m.content.toLowerCase().includes(q.toLowerCase()))).map(c=>({id:c.id,folder_id:c.folder_id||null,title:c.title,custom_title:c.custom_title||0,pinned_at:c.pinned_at||null,archived_at:c.archived_at||null,created_at:c.created_at,updated_at:c.updated_at,message_count:c.messages.length,preview:c.messages.at(-1)?.content||''}));payload={ok:true,conversations:list,folders:window.__backend.folders.map(f=>({...f,conversation_count:window.__backend.conversations.filter(c=>c.folder_id===f.id).length}))}}
 }
 else if(path==='/api/conversations'&&method==='POST'){const id=(window.__backend.conversations.length+1).toString(16).padStart(32,'0');const t=Date.now();const c={id,folder_id:body.folder_id||null,title:body.title||'Новый чат',custom_title:0,pinned_at:null,archived_at:null,created_at:t,updated_at:t,messages:[]};window.__backend.conversations.unshift(c);status=201;payload={ok:true,conversation:c};}
 else if(path==='/api/conversations/import'&&method==='POST'){let imported=0;for(const raw of (body.conversations||[])){const id=(window.__backend.conversations.length+1).toString(16).padStart(32,'0');const t=Date.now();window.__backend.conversations.push({id,title:raw.title||'Новый чат',folder_id:null,custom_title:0,created_at:t,updated_at:t,messages:(raw.messages||[]).map((m,i)=>({id:'m'+i,role:m.role,content:m.content,kind:m.kind||'message',sources:m.sources||[],attachments:m.attachments||[],created_at:t+i}))});imported++}payload={ok:true,imported,skipped:0};}
 else if(path.startsWith('/api/conversations/')&&path.endsWith('/share')&&method==='POST'){const id=path.split('/').filter(Boolean)[2];const c=window.__backend.conversations.find(x=>x.id===id);if(!c){status=404;payload={error:'conversation not found'}}else{const share={id:'share-'+(window.__backend.shares.length+1),title:c.title,created_at:Math.floor(Date.now()/1000),expires_at:Math.floor(Date.now()/1000)+Number(body.ttl_seconds||604800),url:'http://127.0.0.1:3100/share/browser-test'};window.__backend.shares.push(share);status=201;payload={ok:true,share}}}
 else if(path.startsWith('/api/conversations/')&&method==='POST'){const parts=path.split('/').filter(Boolean),id=parts[2],action=parts[3],c=window.__backend.conversations.find(x=>x.id===id);if(!c){status=404;payload={error:'conversation not found'}}else if(action==='rename'){c.title=body.title;c.custom_title=1;c.updated_at=Date.now();payload={ok:true,conversation:c}}else if(action==='clear'){c.messages=[];c.title='Новый чат';c.custom_title=0;c.updated_at=Date.now();payload={ok:true,conversation:c}}else if(action==='messages'){const m={id:'m'+(c.messages.length+1),role:body.role,content:body.content,kind:body.kind||'message',sources:body.sources||[],attachments:body.attachments||[],created_at:Date.now()};c.messages.push(m);c.updated_at=Date.now();if(body.role==='user'&&!c.custom_title&&c.title==='Новый чат')c.title=String(body.content||'').slice(0,46);status=201;payload={ok:true,message:m}}else if(action==='move'){c.folder_id=body.folder_id||null;payload={ok:true,conversation:c}}else if(action==='pin'){c.pinned_at=body.pinned?Date.now():null;payload={ok:true,conversation:c}}else if(action==='archive'){c.archived_at=body.archived?Date.now():null;if(body.archived)c.pinned_at=null;payload={ok:true,conversation:c}}else payload={ok:true,conversation:c};}
 else if(path.startsWith('/api/conversations/')&&method==='DELETE'){const id=path.split('/').filter(Boolean)[2];window.__backend.conversations=window.__backend.conversations.filter(x=>x.id!==id);payload={ok:true};}
 else if(path==='/api/folders'&&method==='POST'){const id='f'+(window.__backend.folders.length+1).toString(16).padStart(31,'0');const f={id,name:body.name,created_at:Date.now(),updated_at:Date.now(),conversation_count:0};window.__backend.folders.push(f);status=201;payload={ok:true,folder:f};}
 else if(path.startsWith('/api/folders/')&&path.endsWith('/rename')&&method==='POST'){const id=path.split('/')[3];const f=window.__backend.folders.find(x=>x.id===id);if(!f){status=404;payload={error:'folder not found'}}else{f.name=body.name;f.updated_at=Date.now();payload={ok:true,folder:{...f,conversation_count:window.__backend.conversations.filter(c=>c.folder_id===id&&!c.archived_at).length}}}}
 else if(path.startsWith('/api/folders/')&&method==='DELETE'){const id=path.split('/')[3];window.__backend.conversations.forEach(c=>{if(c.folder_id===id)c.folder_id=null});window.__backend.folders=window.__backend.folders.filter(f=>f.id!==id);payload={ok:true};}
 else if(path==='/api/onboarding'&&method==='GET')payload={ok:true,persona:'user',state:window.__backend.onboarding.user};
 else if(path==='/api/onboarding?persona=admin'&&method==='GET')payload={ok:true,persona:'admin',state:window.__backend.onboarding.admin};
 else if(path==='/api/onboarding'&&method==='POST'){const persona=body.persona==='admin'?'admin':'user';window.__backend.onboarding[persona]={status:body.status,current_step:body.current_step||0,tour_version:1};payload={ok:true,persona,state:window.__backend.onboarding[persona]};}
 else if(path==='/api/billing/plans')payload={plans:[{id:'LIGHT',display_name:'Лайт',price_rub:0,support_level:'community',local_unlimited:true,remote_token_limit:0,remote_cost_limit_rub:0,enabled:true},{id:'MEDIUM',display_name:'Медиум',price_rub:500,support_level:'standard',local_unlimited:true,remote_token_limit:100000,remote_cost_limit_rub:50,enabled:true},{id:'PRO',display_name:'Про',price_rub:1000,support_level:'priority',local_unlimited:true,remote_token_limit:500000,remote_cost_limit_rub:250,enabled:true}]};
 else if(path==='/api/billing/me')payload={plan:{id:'LIGHT',display_name:'Лайт',price_rub:0,support_level:'community',local_unlimited:true,remote_token_limit:0,remote_cost_limit_rub:0,enabled:true},subscription:{plan_id:'LIGHT',status:'ACTIVE',auto_renew:false,cancel_at_period_end:false,billing_exempt:false},usage:{by_class:{LOCAL:{total_tokens:1250,estimated_cost_rub:0}},total:{total_tokens:1250,estimated_cost_rub:0}},quota:{platform_remote_tokens_used:0,platform_remote_tokens_limit:0,platform_remote_tokens_remaining:0,platform_remote_cost_rub_used:0,platform_remote_cost_rub_limit:0,platform_remote_cost_rub_remaining:0},preferences:{show_token_usage:window.__backend.showTokens},payment:{configured:false,provider:'disabled'}};
 else if(path==='/api/billing/preferences'&&method==='POST'){window.__backend.showTokens=!!body.show_token_usage;payload={show_token_usage:window.__backend.showTokens};}
 else if(path==='/api/billing/checkout'&&method==='POST'){status=503;payload={error:'payment provider is not configured'};}
 else if(path==='/api/health')payload={ready:true,engine:'ready',inference:'ready'};
 else if(path==='/api/chat'){
   window.__backend.chatCalls++;const latest=(body.messages||[]).filter(x=>x.role==='user').at(-1)?.content||'';window.__backend.lastMode=body.mode;window.__backend.lastPreset=body.preset||'none';window.__backend.lastFileIds=body.file_ids||[];
   let text='PAR_TEST_OK',sources=[],scenario=null,intent='chat';const pending=body.conversation_id?window.__backend.scenarioPending[body.conversation_id]:null;const requested=body.scenario_id||pending;
   if(requested==='clothing'&&!pending){scenario=window.__backend.scenarios.find(x=>x.id==='clothing');if(body.conversation_id)window.__backend.scenarioPending[body.conversation_id]='clothing';text='Чтобы подобрать действительно подходящие варианты, уточните одним сообщением: размер или основные мерки, примерный бюджет, сезон/повод и что точно не нравится.';intent='clarification';}
   else{
     if(requested==='clothing'){scenario=window.__backend.scenarios.find(x=>x.id==='clothing');if(body.conversation_id)delete window.__backend.scenarioPending[body.conversation_id];text='PAR_SCENARIO_WEB_OK';sources=[{title:'Одежда fixture',url:'https://example.org/clothing',status:'retrieved',strategy:'browser'}];intent='search';}
     if(String(latest).includes('PAR_XSS'))text='<img src=x onerror=window.__parXss=1>';
     if(String(latest).includes('PAR_MARKDOWN'))text='### Ответ\n\n**Жирный** текст и `код`.\n\n```python\nprint("ok")\n```';
     if(String(latest).trim().toLowerCase()==='ок')text='Хорошо.';
     if(!scenario&&(String(latest).includes('https://')||body.intent_hint==='search'||body.intent_hint==='research')){text='PAR_WEB_OK';sources=[{title:'DTF fixture',url:'https://dtf.ru/test',domain:'dtf.ru',status:'retrieved',strategy:'browser',kind:'news',summary:'Свежая новость из DTF fixture',published_date:'2026-08-10T12:00:00Z'},{title:'Second source',url:'https://example.org/second',domain:'example.org',status:'retrieved',strategy:'static',kind:'news',summary:'Вторая проверяемая новость',published_date:'2026-08-10T11:00:00Z'}];intent=body.intent_hint||'url';}
   }
   const responseBase={ok:true,mode:body.mode,preset:body.preset||'none',intent,sources};if(scenario)responseBase.scenario=scenario;if(intent==='clarification')responseBase.clarification={round:1,max_rounds:1};
   if(body.conversation_id){const c=window.__backend.conversations.find(x=>x.id===body.conversation_id);if(c){if(body.persist_user){const um={id:'u'+Date.now(),role:'user',content:latest,kind:'message',sources:[],attachments:body.attachments||[],created_at:Date.now()};c.messages.push(um);if(!c.custom_title&&c.title==='Новый чат')c.title=latest.slice(0,46)}const am={id:'a'+Date.now(),role:'assistant',content:text,kind:'message',sources,attachments:[],metadata:{duration_ms:1234,routing_ms:34,web_ms:sources.length?600:0,inference_ms:500,source_count:sources.length,request_id:'req-browser',correlation_id:'corr-browser',intent},created_at:Date.now()+1};c.messages.push(am);c.updated_at=Date.now();payload={...responseBase,message:am,conversation_id:c.id}}else payload={...responseBase,message:{role:'assistant',content:text}};
 }
 }
 else if(path==='/api/tasks'&&method==='POST'){const id='t'+String(Object.keys(window.__backend.tasks).length+1).padStart(31,'0');const task={id,user_id:'local-owner',task_type:'research_report',title:body.question,status:'RUNNING',phase:'web',progress:20,result:null,steps:[]};window.__backend.tasks[id]=task;setTimeout(()=>{window.__backend.tasks[id]={...task,status:'COMPLETED',phase:'completed',progress:100,result:{answer:'REPORT_OK',sources:[{title:'Source',url:'https://example.org/source',status:'retrieved'}],artifacts:[{id:'a1',name:'research-report.md',mime:'text/markdown',sha256:'a'.repeat(64),validation_status:'verified'},{id:'a2',name:'research-sources.xlsx',mime:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',sha256:'b'.repeat(64),validation_status:'verified'},{id:'a3',name:'research-report.pdf',mime:'application/pdf',sha256:'c'.repeat(64),validation_status:'verified'}]}}},80);status=202;payload={ok:true,task};}
 else if(path.startsWith('/api/tasks/')&&method==='GET'){const id=path.split('/')[3];payload={ok:true,task:window.__backend.tasks[id]};}
 else if(path.startsWith('/api/tasks/')&&path.endsWith('/cancel')&&method==='POST'){const id=path.split('/')[3];window.__backend.tasks[id]={...(window.__backend.tasks[id]||{id}),status:'CANCELLED',phase:'cancelled',progress:100};payload={ok:true,cancel_requested:true,task:window.__backend.tasks[id]};}
 else if(path.startsWith('/api/tasks?')&&method==='GET'){payload={ok:true,tasks:Object.values(window.__backend.tasks)};}
 else if(path==='/api/code/status')payload={ok:true,ready:true,network:'disabled',languages:[{id:'python',label:'Python',available:true},{id:'java',label:'Java 21',available:true},{id:'powershell',label:'PowerShell',available:true}]};
 else if(path==='/api/code/jobs'&&method==='POST'){const id='c'+String(Object.keys(window.__backend.codeJobs).length+1).padStart(31,'0');const job={id,language:body.language,status:'QUEUED',progress:0,error:null};window.__backend.codeJobs[id]=job;setTimeout(()=>{window.__backend.codeJobs[id]={...job,status:'COMPLETED',progress:100,result:{exit_code:0,duration_ms:12,stdout:'CODE_OK\n',stderr:'',output_truncated:false,timed_out:false,cancelled:false}}},80);status=202;payload={ok:true,job};}
 else if(path.startsWith('/api/code/jobs/')&&path.endsWith('/cancel')&&method==='POST'){const id=path.split('/')[4];window.__backend.codeJobs[id]={...(window.__backend.codeJobs[id]||{id}),status:'CANCELLED',progress:100,error:'cancelled'};payload={ok:true,job:window.__backend.codeJobs[id]};}
 else if(path.startsWith('/api/code/jobs/')&&method==='GET'){const id=path.split('/').at(-1);payload={ok:true,job:window.__backend.codeJobs[id]||{id,status:'FAILED',error:'missing'}};}
 else if(path==='/api/files'&&method==='GET')payload={ok:true,artifacts:JSON.parse(JSON.stringify(window.__backend.artifacts))};
 else if(path==='/api/files/upload'&&method==='POST'){const id='file-'+(window.__backend.artifacts.length+1);const item={artifact_id:id,name:'fixture.txt',format:'txt',size:42,version:1,validation_status:'verified',sha256:'a'.repeat(64),download_url:'/api/files/'+id+'/download'};window.__backend.artifacts.unshift(item);status=201;payload={ok:true,artifact:item};}
 else if(path==='/api/files/create'&&method==='POST'){const id='file-'+(window.__backend.artifacts.length+1);const item={artifact_id:id,name:body.name||('document.'+body.format),format:body.format,size:128,version:1,validation_status:'verified',sha256:'b'.repeat(64),download_url:'/api/files/'+id+'/download'};window.__backend.artifacts.unshift(item);status=201;payload={ok:true,artifact:item};}
 else if(path.startsWith('/api/files/')&&method==='DELETE'){const id=path.split('/').at(-1);window.__backend.artifacts=window.__backend.artifacts.filter(x=>x.artifact_id!==id);payload={ok:true};}
 else if(path==='/api/admin/login'){if(body.token!=='browser-admin-token-123'){status=401;payload={error:'invalid admin token'}}else payload={ok:true};}
 else if(path==='/api/admin/auth-status')payload={ok:true,account_admin:['OWNER','ADMIN'].includes(window.__backend.authRole),break_glass_configured:true,auth_mode:window.__backend.authMode};
 else if(path==='/api/admin/feedback'){if(!adminOk){status=401;payload={error:'admin authorization required'}}else payload={ok:true,items:JSON.parse(JSON.stringify(window.__backend.feedback))};}
 else if(path==='/api/admin/status'){if(!adminOk){status=401;payload={error:'admin authorization required'}}else payload={product:'Personal Agent Rus',product_family:'Personal Agent',edition:'rus',locale:'ru-RU',version:'0.8.0-alpha.8',bootstrap_model:'qwen3:0.6b',routing:JSON.parse(JSON.stringify(window.__backend.routing)),providers:JSON.parse(JSON.stringify(window.__backend.providers)),provider_status:window.__backend.providers.map(p=>({provider_id:p.id,healthy:true,model_count:window.__backend.inventory.filter(m=>m.provider_id===p.id).length,error:null})),model_inventory:JSON.parse(JSON.stringify(window.__backend.inventory)),installed_models:window.__backend.inventory.filter(m=>m.provider_id==='local-ollama').map(m=>({name:m.model_id,size:m.size})),auth_mode:'personal',registration_policy:'open',setup_complete:false};}
 else if(path==='/api/admin/users'){if(!adminOk){status=401;payload={error:'admin authorization required'}}else payload={users:window.__backend.users,auth_mode:'personal',registration_policy:'open'};}
 else if(path==='/api/admin/billing'){if(!adminOk){status=401;payload={error:'admin authorization required'}}else payload={plans:[{id:'LIGHT',display_name:'Лайт',price_rub:0,support_level:'community',local_unlimited:true,remote_token_limit:0,remote_cost_limit_rub:0},{id:'MEDIUM',display_name:'Медиум',price_rub:500,support_level:'standard',local_unlimited:true,remote_token_limit:100000,remote_cost_limit_rub:50},{id:'PRO',display_name:'Про',price_rub:1000,support_level:'priority',local_unlimited:true,remote_token_limit:500000,remote_cost_limit_rub:250}],payment_config:{provider:'disabled',shop_id:'',public_base_url:'',has_secret:false,configured:false,webhook_path:'/api/billing/webhook/yookassa'},usage:[{billing_class:'LOCAL',provider_id:'local-ollama',model_id:'qwen3:0.6b',tokens:1250,estimated_cost_rub:0,events:2}]};}
 else if(path.startsWith('/api/admin/billing/plans/')&&method==='POST'){payload={ok:true,plan:{id:path.split('/').at(-1),remote_token_limit:Number(body.remote_token_limit||0),remote_cost_limit_rub:Number(body.remote_cost_limit_rub||0)}};}
 else if(path==='/api/admin/billing/payment-config'&&method==='POST'){payload={ok:true,payment_config:{provider:body.provider||'disabled',shop_id:body.shop_id||'',public_base_url:body.public_base_url||'',has_secret:Boolean(body.secret_key),configured:(body.provider==='yookassa'&&Boolean(body.shop_id&&body.public_base_url&&body.secret_key)),webhook_path:'/api/billing/webhook/yookassa'}};}
 else if(path==='/api/admin/site-profiles'&&method==='GET'){if(!adminOk){status=401;payload={error:'admin authorization required'}}else payload={ok:true,profiles:JSON.parse(JSON.stringify(window.__backend.siteProfiles))};}
 else if(path.startsWith('/api/admin/site-profiles/')&&method==='POST'){if(!adminOk){status=401;payload={error:'admin authorization required'}}else{const id=path.split('/').at(-1),i=window.__backend.siteProfiles.findIndex(x=>x.id===id);if(i<0){status=404;payload={error:'site profile not found'}}else{window.__backend.siteProfiles[i]={...window.__backend.siteProfiles[i],enabled:body.enabled!==false,acquisition_order:body.acquisition_order||window.__backend.siteProfiles[i].acquisition_order,egress_region:body.egress_region||window.__backend.siteProfiles[i].egress_region};payload={ok:true,profile:window.__backend.siteProfiles[i]}}}}
 else if(path==='/api/admin/observability'){payload={ok:true,observability:{version:'0.8.0-alpha.8',runtime_profile:'local',uptime_seconds:123,load:[0.1,0.2,0.3],disk:{free_bytes:1000,total_bytes:2000},db_size_bytes:1234,counts:{tasks_active:0,artifacts:3}}};}
 else if(path.startsWith('/api/admin/logs'))payload={ok:true,events:[{timestamp:'2026-08-10T00:00:00Z',level:'INFO',service:'core',event:'chat.completed',request_id:'req-browser',status:'SUCCESS'}]};
 else if(path.startsWith('/api/admin/audit'))payload={ok:true,events:[{action:'routing.update',details:{mode:'smart'},created_at:1786339200}]};
 else if(path==='/api/admin/diagnostics')payload={ok:true,diagnostics:{product:'Personal Agent Rus',version:'0.8.0-alpha.8',runtime_profile:'local',auth_mode:window.__backend.authMode,db_size_bytes:1234,log_dir:'/data/logs',recent_events:[{event:'chat.completed',request_id:'req-browser'}]}};
 else if(path==='/api/admin/deployments/fingerprint'&&method==='POST'){payload={ok:true,fingerprint:{type:'ssh-ed25519',sha256:'SHA256:BROWSERTEST'}};}
 else if(path==='/api/admin/deployments'&&method==='POST'){const item={id:'d'+String(window.__backend.deployments.length+1).padStart(31,'0'),name:body.name,host:body.host,port:body.port,username:body.username,domain:body.domain,profile:body.profile,host_key_sha256:body.host_key_sha256,last_status:'NEW',last_message:''};window.__backend.deployments.push(item);status=201;payload={ok:true,target:item};}
 else if(path==='/api/admin/deployments'&&method==='GET'){payload={ok:true,targets:window.__backend.deployments,profiles:[{id:'server-lite',label:'Слабый VPS'},{id:'server-standard',label:'Обычный VPS'}]};}
 else if(path==='/api/admin/providers'){if(!adminOk){status=401;payload={error:'admin authorization required'}}else if(method==='POST'){const id=window.__backend.providers.some(p=>p.id==='provider-test')?'provider-test-2':'provider-test';window.__backend.providers.push({id,name:body.name,type:body.type,base_url:body.base_url,enabled:1,managed_by:'admin',has_secret:Boolean(body.api_key),billing_class:body.billing_class||'BYOK',cost_input_per_million_rub:Number(body.cost_input_per_million_rub||0),cost_output_per_million_rub:Number(body.cost_output_per_million_rub||0)});window.__backend.inventory.push({provider_id:id,provider_name:body.name,provider_type:body.type,model_id:'external-model',display_name:'external-model',size:0,available:true,source:'discovery'});status=201;payload={ok:true,provider:{id,name:body.name,type:body.type,base_url:body.base_url,model_count:1,has_secret:Boolean(body.api_key)}}}else payload={providers:window.__backend.providers,inventory:window.__backend.inventory};}
 else if(path.startsWith('/api/admin/providers/')&&path.endsWith('/test'))payload={ok:true,provider_id:path.split('/').at(-2),model_count:1};
 else if(path.startsWith('/api/admin/providers/')&&method==='DELETE'){const id=path.split('/').at(-1);window.__backend.providers=window.__backend.providers.filter(p=>p.id!==id);window.__backend.inventory=window.__backend.inventory.filter(m=>m.provider_id!==id);payload={ok:true};}
 else if(path==='/api/admin/routing'&&method==='POST'){window.__backend.routing={...window.__backend.routing,...body.routing};payload={ok:true};}
 else if(path==='/api/admin/models/pull'&&method==='POST'){window.__backend.inventory.push({provider_id:body.provider_id||'local-ollama',provider_name:'Локальный Ollama',provider_type:'ollama',model_id:body.model,display_name:body.model,size:1000000,available:true,source:'discovery'});window.__backend.jobs.j1={id:'j1',status:'completed',progress:100,message:'Модель готова'};status=202;payload={ok:true,job_id:'j1'};}
 else if(path==='/api/admin/jobs/j1')payload=window.__backend.jobs.j1;
 else{status=404;payload={error:'not found'}}
 return new Response(JSON.stringify(payload),{status,headers:{'Content-Type':'application/json'}});
};
'''

def chromium_path():
    override=os.getenv('PA_TEST_CHROMIUM')
    if override:return override
    for name in ('chromium','chromium-browser','google-chrome','google-chrome-stable'):
        path=shutil.which(name)
        if path:return path
    return None

def install_storage(page,name,initial=None):
    initial=initial or {};script=f"Object.defineProperty(window,{json.dumps(name)},{{configurable:true,value:{{d:{json.dumps(initial,ensure_ascii=False)},setItem(k,v){{this.d[k]=String(v)}},getItem(k){{return Object.prototype.hasOwnProperty.call(this.d,k)?this.d[k]:null}},removeItem(k){{delete this.d[k]}},clear(){{this.d={{}}}}}}}});";page.evaluate(script)

def load_user(page,storage=None):
    page.set_content(INDEX);install_storage(page,'localStorage',storage);install_storage(page,'sessionStorage',{});page.add_style_tag(content=CSS);page.add_script_tag(content=BACKEND_STUB);page.add_script_tag(content=APP);expect(page.locator('#modes .mode')).to_have_count(3)

def load_admin(page,storage=None):
    page.set_content(ADMIN);install_storage(page,'localStorage',{});install_storage(page,'sessionStorage',storage);page.add_style_tag(content=CSS);page.add_script_tag(content=BACKEND_STUB);page.add_script_tag(content=ADMIN_JS)

def load_account(page):
    page.set_content(ACCOUNT);install_storage(page,'localStorage',{});page.add_style_tag(content=CSS);page.add_script_tag(content=BACKEND_STUB);page.add_script_tag(content=AUTH_JS)

def main():
    exe=chromium_path()
    if not exe:raise SystemExit('No Chromium/Chrome executable found; set PA_TEST_CHROMIUM')
    driver_pid=None
    with sync_playwright() as p:
        driver_pid=getattr(getattr(getattr(getattr(p,'_impl_obj',None),'_connection',None),'_transport',None),'_proc',None)
        driver_pid=getattr(driver_pid,'pid',None)
        globals()['_last_playwright_driver_pid']=driver_pid
        browser=p.chromium.launch(headless=True,executable_path=exe,args=['--no-sandbox'])
        context=browser.new_context(viewport={'width':1440,'height':900})
        def new_page(**kwargs):
            page=context.new_page()
            viewport=kwargs.get('viewport')
            if viewport: page.set_viewport_size(viewport)
            return page
        page=new_page(viewport={'width':1440,'height':900});load_user(page)
        assert page.title()=='Родной Агент';body=page.locator('body').inner_text().lower();assert page.locator('#sidebar').is_visible();assert page.locator('#accountEntry').is_visible();expect(page.locator('#adminEntry')).to_be_hidden();expect(page.locator('#modeButton')).to_be_visible();expect(page.locator('#newFolder')).to_be_visible();expect(page.locator('#brandHelp')).to_be_visible();assert page.locator('#sidebarResizer').count()==1
        page.keyboard.press('Control+b');expect(page.locator('#sidebar')).to_have_class(re.compile('collapsed'));page.keyboard.press('Control+b');expect(page.locator('#sidebar')).not_to_have_class(re.compile('collapsed'))
        page.locator('#brandHelp').click();expect(page.locator('#helpBackdrop')).to_be_visible();page.locator('#restartTour').click();expect(page.locator('#tourLayer')).to_be_visible();expect(page.locator('#tourProgress')).to_contain_text('1 из');page.locator('#tourSkip').click();expect(page.locator('#tourLayer')).to_be_hidden()
        # Alpha.4 shell hardening: collapsed rail is clean; language/theme/execution/tone are user controls.
        page.keyboard.press('Control+b');expect(page.locator('#folders')).to_be_hidden();expect(page.locator('#conversations')).to_be_hidden();assert page.locator('#sidebar').bounding_box()['width']<=70;page.keyboard.press('Control+b')
        page.locator('#settingsEntry').click();page.locator('#uiLanguage').select_option('en');page.locator('#responseLanguage').select_option('ru');page.locator('#themeSelect').select_option('light');page.locator('#executionPolicy').select_option('local_only');page.locator('#tonePreset').select_option('meme');page.locator('#saveExperiencePreferences').click();expect(page.locator('#experienceState')).to_contain_text('Saved');assert page.evaluate("document.documentElement.dataset.theme")=='light';expect(page.locator('#newChat')).to_contain_text('New chat');expect(page.locator('#brandName')).to_have_text('Personal Agent');assert page.title()=='Personal Agent';assert page.evaluate("window.__backend.experiencePreferences.execution_policy")=='local_only';page.locator('#closeSettings').click();page.locator('#toneButton').click();expect(page.locator('#toneMenu')).to_be_visible();page.locator('#toneMenu button').filter(has_text='Meme').click();assert page.evaluate("window.__backend.experiencePreferences.tone")=='meme'
        page.locator('#settingsEntry').click();page.locator('#uiLanguage').select_option('ru');page.locator('#themeSelect').select_option('dark');page.locator('#executionPolicy').select_option('auto');page.locator('#tonePreset').select_option('normal');page.locator('#saveExperiencePreferences').click();page.locator('#closeSettings').click();expect(page.locator('#newChat')).to_contain_text('Новый чат');expect(page.locator('#brandName')).to_have_text('Родной Агент');assert page.title()=='Родной Агент'
        for secret in ('qwen','ollama','provider_id','model_id'):assert secret not in body,secret
        print('[BROWSER] shell/help ready',flush=True)
        # Scenario Gallery is a beginner entry point backed by the same chat flow, with bounded clarification.
        scenario_page=new_page(viewport={'width':1280,'height':820});load_user(scenario_page);expect(scenario_page.locator('.scenario-card')).to_have_count(2);scenario_page.locator('.scenario-card[data-scenario="clothing"]').click();expect(scenario_page.locator('#input')).to_have_value('Подбери мне одежду под мои параметры и бюджет.');scenario_page.locator('#send').click();expect(scenario_page.locator('#capabilityBanner')).to_contain_text('Нужно одно короткое уточнение');expect(scenario_page.locator('.msg.assistant').last).to_contain_text('размер');scenario_page.locator('#input').fill('Мужчина, XL, до 15000 рублей, на лето');scenario_page.locator('#send').click();expect(scenario_page.locator('.msg.assistant').last).to_contain_text('PAR_SCENARIO_WEB_OK');expect(scenario_page.locator('#capabilityBanner')).to_have_text('');
        scenario_page.locator('#settingsEntry').click();scenario_page.locator('[data-settings-tab="web"]').click();scenario_page.locator('#webSearchScope').select_option('selected');scenario_page.locator('#webRegion').fill('Москва');scenario_page.locator('#webAllowedDomains').fill('cian.ru\nzakupki.gov.ru');scenario_page.locator('#webExcludedDomains').fill('example.com');scenario_page.locator('#saveWebPreferences').click();assert scenario_page.evaluate("window.__backend.webPreferences.search_scope")=='selected';assert scenario_page.evaluate("window.__backend.webPreferences.region")=='Москва';assert scenario_page.evaluate("window.__backend.webPreferences.allowed_domains.join(',')")=='cian.ru,zakupki.gov.ru';scenario_page.close();print('[BROWSER] scenarios/site-preferences ready',flush=True)
        # Structured preset is independent from Smart mode.
        page.locator('.starter-card[data-preset="analyze"]').click();page.locator('#modeButton').click();page.get_by_role('button',name='Умно',exact=True).click();page.locator('#input').fill('ок');page.locator('#send').click();expect(page.locator('.msg.assistant')).to_have_count(1);assert 'Хорошо' in page.locator('.msg.assistant').last.inner_text();assert page.evaluate('window.__backend.lastMode')=='smart';assert page.evaluate('window.__backend.lastPreset')=='analyze'
        # Quality UI: user message is not rendered with duplicate 'Вы', and chat export is visible + persisted as a workspace artifact.
        assert page.locator('.message-row.user .message-author').count()==0
        expect(page.locator('#shareChatButton')).to_be_visible();page.locator('#shareChatButton').click();expect(page.locator('#actionBackdrop')).to_be_visible();page.locator('#actionSelect').select_option('86400');page.locator('#actionConfirm').click();assert page.evaluate('window.__backend.shares.length')==1
        page.locator('#feedbackEntry').click();expect(page.locator('#helpBackdrop')).to_be_visible();expect(page.locator('#feedbackInline')).to_be_visible();page.locator('#feedbackCategory').select_option('ux');page.locator('#feedbackRating').select_option('5');page.locator('#feedbackMessage').fill('UX alpha4 browser feedback');page.locator('#sendFeedback').click();expect(page.locator('#feedbackState')).to_contain_text('Спасибо');assert page.evaluate('window.__backend.feedback.length')==1;page.locator('#closeHelp').click()
        expect(page.locator('#exportChatButton')).to_be_visible();before_export=page.evaluate('window.__backend.artifacts.length');page.evaluate('HTMLAnchorElement.prototype.click=function(){}');page.locator('#exportChatButton').click();
        for _ in range(40):
            if page.evaluate('window.__backend.artifacts.length')==before_export+1: break
            page.wait_for_timeout(25)
        assert page.evaluate('window.__backend.artifacts.length')==before_export+1;assert page.evaluate('window.__backend.artifacts[0].format')=='md';page.locator('#settingsEntry').click();page.locator('[data-settings-tab="data"]').click();before_all=page.evaluate('window.__backend.artifacts.length');page.locator('#exportAllChats').click();expect(page.locator('#artifactList .artifact-row')).to_have_count(before_all+1);assert page.evaluate('window.__backend.artifacts[0].format')=='json';page.locator('#closeSettings').click()
        page.locator('#input').fill('PAR_MARKDOWN');page.locator('#send').click();expect(page.locator('.code-block')).to_have_count(1)
        page.locator('#newChat').click();page.locator('.starter-card[data-intent="research"]').click();page.locator('#input').fill('Что нового на https://dtf.ru/');page.locator('#send').click();expect(page.locator('.msg.assistant')).to_have_count(1);expect(page.locator('.message-sources .source-card')).to_have_count(2);expect(page.locator('.result-card')).to_have_count(2);expect(page.locator('.message-meta')).to_contain_text('1.2 s');assert 'PAR_WEB_OK' in page.locator('.msg.assistant').last.inner_text()
        print('[BROWSER] chat/web/export ready',flush=True)
        # Real Files UI journey: tool -> upload -> attachment -> chat context -> workspace list -> create.
        page.locator('#attachBtn').click();expect(page.locator('#toolTray')).to_be_visible();page.locator('[data-tool="files"]').click();page.locator('#fileInput').set_input_files({'name':'notes.txt','mimeType':'text/plain','buffer':b'fixture text'});expect(page.locator('#attachmentBar .attachment-chip')).to_have_count(1);page.locator('#input').fill('Проанализируй файл');page.locator('#send').click();expect(page.locator('.message-attachments .message-file')).to_have_count(1);assert page.evaluate('window.__backend.lastFileIds.length')==1
        page.locator('#filesEntry').click();expect(page.locator('[data-settings-panel="files"]')).to_have_class(re.compile('active'));artifact_count=page.evaluate('window.__backend.artifacts.length');expect(page.locator('#artifactList .artifact-row')).to_have_count(artifact_count);page.locator('#artifactFormat').select_option('pdf');page.locator('#artifactName').fill('report.pdf');page.locator('#artifactContent').fill('Тестовый PDF');page.locator('#createArtifact').click();expect(page.locator('#artifactList .artifact-row')).to_have_count(artifact_count+1);page.locator('#closeSettings').click()
        print('[BROWSER] files ready',flush=True)
        # Code UI journey: open sandbox, execute, poll result.
        page.locator('#codeEntry').click();expect(page.locator('[data-settings-panel="code"]')).to_have_class(re.compile('active'));expect(page.locator('#codeRunState')).to_contain_text('Sandbox');page.locator('#codeLanguage').select_option('python');page.locator('#codeEditor').fill('print("CODE_OK")');page.locator('#runCode').click();expect(page.locator('#codeStdout')).to_contain_text('CODE_OK',timeout=5000);expect(page.locator('#codeRunState')).to_contain_text('COMPLETED');page.locator('#closeSettings').click()
        print('[BROWSER] code ready',flush=True)
        page.locator('#newFolder').click();page.locator('#actionInput').fill('Работа');page.locator('#actionConfirm').click();expect(page.locator('#folders .folder-item')).to_have_count(3);expect(page.locator('#folders')).to_contain_text('Работа')
        folder_row=page.locator('#folders .folder-item[data-folder-id]').first;folder_row.locator('.folder-mini').first.click();page.locator('#actionInput').fill('Проект Alpha');page.locator('#actionConfirm').click();expect(page.locator('#folders')).to_contain_text('Проект Alpha')
        page.locator('#newChat').click();page.locator('#input').fill('Второй отдельный диалог');page.locator('#send').click();page.locator('#chatMenuButton').click();page.locator('#chatMenu [data-action="rename"]').click();page.locator('#actionInput').fill('Рабочий чат');page.locator('#actionConfirm').click();expect(page.locator('#conversationTitle')).to_have_text('Рабочий чат')
        page.locator('#chatMenuButton').click();page.locator('#chatMenu [data-action="pin"]').click();expect(page.locator('.conversation-item.active .conversation-icon')).to_have_text('◆')
        page.locator('#chatMenuButton').click();page.locator('#chatMenu [data-action="move"]').click();page.locator('#actionSelect').select_option(label='Проект Alpha');page.locator('#actionConfirm').click();expect(page.locator('#folders')).to_contain_text('Проект Alpha')
        page.locator('#chatSearch').fill('Рабочий');expect(page.locator('.conversation-item')).to_have_count(1);page.locator('#chatSearch').fill('')
        page.locator('#chatMenuButton').click();page.locator('#chatMenu [data-action="archive"]').click();expect(page.locator('#folders')).to_contain_text('Архив · 1');page.get_by_role('button',name=re.compile('Архив')).click();expect(page.locator('.conversation-item')).to_have_count(1);page.locator('#chatMenuButton').click();expect(page.locator('#chatMenu [data-action="archive"]')).to_have_text('Вернуть из архива');page.locator('#chatMenu [data-action="archive"]').click();page.get_by_role('button',name='Все чаты').click()
        folder_row=page.locator('#folders .folder-item[data-folder-id]').first;folder_row.locator('.folder-mini').nth(1).click();page.locator('#actionConfirm').click();expect(page.locator('#folders')).not_to_contain_text('Проект Alpha')
        page.locator('#settingsEntry').click();expect(page.locator('#settingsBackdrop')).to_be_visible();expect(page.locator('#adminSettingsLink')).to_be_visible();page.locator('#closeSettings').click()
        before_xss=page.locator('.msg.assistant').count();page.locator('#input').fill('PAR_XSS');page.locator('#send').click();expect(page.locator('.msg.assistant')).to_have_count(before_xss+1);assert '<img src=x onerror=window.__parXss=1>' in page.locator('.msg.assistant').last.inner_text();assert page.locator('#chat img').count()==0;assert page.evaluate('window.__parXss') is None
        print('[BROWSER] history/projects ready',flush=True)
        mobile=new_page(viewport={'width':390,'height':844});load_user(mobile);mobile.locator('#openSidebar').click();mobile.wait_for_timeout(260);expect(mobile.locator('#sidebar')).to_be_visible();assert mobile.locator('#accountEntry').count()==1;expect(mobile.locator('#adminEntry')).to_be_hidden()
        mobile_tour=new_page(viewport={'width':390,'height':844});mobile_tour.set_content(INDEX);install_storage(mobile_tour,'localStorage',{});install_storage(mobile_tour,'sessionStorage',{});mobile_tour.add_style_tag(content=CSS);mobile_tour.add_script_tag(content=BACKEND_STUB);mobile_tour.evaluate("window.__backend.onboarding.user={status:'not_started',current_step:0,tour_version:1}");mobile_tour.add_script_tag(content=APP);expect(mobile_tour.locator('#tourLayer')).to_be_visible();box=mobile_tour.locator('#tourCard').bounding_box();assert box and box['x']>=0 and box['y']>=0 and box['x']+box['width']<=391 and box['y']+box['height']<=845;mobile_tour.locator('#tourSkip').click();mobile_tour.close()
        mobile.close();print('[BROWSER] mobile ready',flush=True)
        account=new_page(viewport={'width':1100,'height':800});load_account(account);expect(account.locator('#billingAccount')).to_be_visible();expect(account.locator('#currentPlan')).to_have_text('Лайт');prices=account.locator('.plan-price').all_inner_texts();assert 'Бесплатно' in prices and '500 ₽/мес' in prices and '1000 ₽/мес' in prices;assert 'Локально' in account.locator('#usageSummary').inner_text();account.locator('#showTokens').check();assert account.evaluate('window.__backend.showTokens') is True
        account.close();print('[BROWSER] account ready',flush=True)
        try: context.close()
        except Exception: pass
        browser.close()
    print('PAR_V080_BROWSER_ACCEPTANCE PASS: shell scenarios-site-preferences chat-export presets web-research files code-sandbox tasks history mobile account',flush=True)
    return 0

if __name__=='__main__':
    raise SystemExit(main())
